name: R-CMD-Check and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Install qpdf (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install qpdf

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true


  deploy:
    runs-on: ubuntu-latest
    needs: R-CMD-check  # This ensures deployment only happens after checks pass
    if: ${{ success() }}  # This ensures deployment only if all checks succeed

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Deploy Shiny App
        env:
          RSCONNECT_NAME: ${{ secrets.RSCONNECT_NAME }}
          RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
          RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
        run: |
          Rscript inst/deploy/deploy.R
